AppBundle\Entity\Delivery:
    type: entity
    table: delivery
    id:
        deliveryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: delivery_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        deliveryAdress:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: delivery_adress
        deliveryZipCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: delivery_zip_code
        deliveryCity:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: delivery_city
        deliveryCountry:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: delivery_country
    lifecycleCallbacks: {  }
