AppBundle\Entity\Images:
    type:  entity
    table: images
    id:
        id:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            generator:
                strategy: IDENTITY
    fields:
        productId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            column:   product_id
        source:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
        alt:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
    lifecycleCallbacks: {  }
