AppBundle\Entity\PowerSupply:
    type: entity
    table: power_supply
    id:
        powerSupplyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: power_supply_id
            generator:
                strategy: IDENTITY
    fields:
        powerSupplyPower:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: power_supply_power
        powerSupplyModularity:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: power_supply_modularity
        powerSupplyCertification:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: power_supply_certification
    lifecycleCallbacks: {  }
